Repository grpc/grpc-swift-protobuf, pull requests merged in 2024-10, with the labels that each got.

#5 Update tests
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Labels: semver/none

#6 Set grpc-swift version to 2.0.0-alpha.1
  Package.swift
Labels: semver/patch

#7 Add deployment targets to the package manifest
  Package.swift
Labels: ⚠️ semver/major

#8 Fix casing of generated services and methods
  Sources/GRPCProtobufCodeGen/CamelCaser.swift
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift
  Tests/GRPCProtobufCodeGenTests/CamelCaserTests.swift
Labels: semver/patch

#9 Depend on `grpc-swift/main`
  Package.swift
Labels: semver/none
