Repository grpc/grpc-swift-protobuf, pull requests merged in 2024-12, with the labels that each got.

#16 Always include the 'SwiftProtobuf' import in generated code
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGenParserTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Labels: semver/patch

#15 Add CI step to check generated code is up-to-date
  .github/workflows/soundness.yml
  dev/check-generated-code.sh
Labels: semver/none

#17 Only generate SwiftProtobuf import for well-known types
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift
  Tests/GRPCProtobufCodeGenTests/Generated/wkt-service.pb
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGenParserTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
  dev/protos/generate.sh
  dev/protos/local/wkt-service.proto
Labels: semver/patch

#18 Bump grpc-swift version
  Package.swift
Labels: semver/patch

#19 Enable MemberImportVisibility check on all targets
  Package.swift
Labels: semver/none

#20 Ignore case for boolean option values in protoc-gen-grpc-swift
  Sources/protoc-gen-grpc-swift/Options.swift
Labels: semver/patch

#21 Make check for bundled protos more resilient
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift
Labels: semver/patch

#23 Use FoundationEssentials where possible
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift
  Sources/protoc-gen-grpc-swift/GenerateGRPC.swift
  Sources/protoc-gen-grpc-swift/Options.swift
Labels: semver/patch

#25 Update release.yml
  .github/release.yml
Labels: semver/none

#24 Bump version
  Package.swift
Labels: 🔨 semver/patch
