Repository grpc/grpc-swift-protobuf, pull requests merged in 2025-03, with the labels that each got.

#50 Rename nightly_6_1 params to nightly_next
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#49 Remove explicit 'GITHUB_ACTIONS=true'
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#40 Code generation command plugin
  Package.swift
  Plugins/GRPCProtobufGenerator/BuildPluginConfig.swift
  Plugins/GRPCProtobufGenerator/BuildPluginError.swift
  Plugins/GRPCProtobufGenerator/Plugin.swift
  Plugins/GRPCProtobufGeneratorCommand/CommandConfig.swift
  Plugins/GRPCProtobufGeneratorCommand/CommandPluginError.swift
  Plugins/GRPCProtobufGeneratorCommand/Plugin.swift
  Plugins/GRPCProtobufGeneratorCommand/PluginsShared
  Plugins/PluginsShared/GenerationConfig.swift
  Plugins/PluginsShared/PluginUtils.swift
Labels: 🆕 semver/minor

#48 Allow module names to be configured
  Package.swift
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenerator.swift
  Sources/protoc-gen-grpc-swift/GenerateGRPC.swift
  Sources/protoc-gen-grpc-swift/Options.swift
  Tests/GRPCProtobufCodeGenTests/Generated/test-service.pb
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGenParserTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
  Tests/GRPCProtobufCodeGenTests/Utilities.swift
  dev/protos/generate.sh
  dev/protos/local/test-service.proto
Labels: 🔨 semver/patch

#51 Don't generate reflection data.
  Sources/protoc-gen-grpc-swift/GenerateGRPC.swift
  Sources/protoc-gen-grpc-swift/Options.swift
Labels: 🔨 semver/patch

#52 Add command plugin to package products
  Package.swift
  Plugins/GRPCProtobufGeneratorCommand/Plugin.swift
Labels: 🆕 semver/minor

#55 Add static SDK CI workflow
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#53 Add `swiftlint:disable all` to leading trivia
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift
  Tests/GRPCProtobufCodeGenTests/Generated/test-service.pb
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGenParserTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
  Tests/GRPCProtobufTests/Errors/Generated/error-service.grpc.swift
Labels: 🔨 semver/patch
