Repository grpc/grpc-swift-protobuf, pull requests merged in 2025-01, with the labels that each got.

#29 Adopt new serializer protocols
  Sources/GRPCProtobuf/Coding.swift
  Sources/GRPCProtobuf/ContiguousBytesAdapter.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
  Tests/GRPCProtobufTests/Errors/Generated/error-service.grpc.swift
  Tests/GRPCProtobufTests/ProtobufCodingTests.swift
Labels: ⚠️ semver/major

#30 Depend on beta 3 tag
  Package.swift
Labels: semver/none

#28 Code generation build plugin
  Package.swift
  Plugins/GRPCProtobufGenerator/BuildPluginConfig.swift
  Plugins/GRPCProtobufGenerator/Plugin.swift
  Plugins/GRPCProtobufGenerator/PluginsShared
  Plugins/PluginsShared/GenerationConfig.swift
  Plugins/PluginsShared/PluginError.swift
  Plugins/PluginsShared/PluginUtils.swift
Labels: 🆕 semver/minor

#32 Remove percent-encoded chars in build plugin paths
  Plugins/PluginsShared/PluginUtils.swift
Labels: 🔨 semver/patch

#33 Fix warnings about unused value in plugin error
  Plugins/PluginsShared/PluginError.swift
Labels: 🔨 semver/patch

#34 Fix deprecations from codegen changes
  Package.swift
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenerator.swift
  Sources/protoc-gen-grpc-swift/GenerateGRPC.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGenParserTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
  Tests/GRPCProtobufCodeGenTests/Utilities.swift
Labels: 🔨 semver/patch

#36 Add an article explaining how to install `protoc`
  Sources/GRPCProtobuf/Documentation.docc/Articles/Installing-protoc.md
  Sources/GRPCProtobuf/Documentation.docc/Documentation.md
Labels: semver/none

#35 Align on config name for use import access level
  Plugins/GRPCProtobufGenerator/BuildPluginConfig.swift
  Plugins/PluginsShared/GenerationConfig.swift
  Plugins/PluginsShared/PluginUtils.swift
Labels: 🔨 semver/patch

#31 Integration tests for the build plugin
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  .licenseignore
  IntegrationTests/PluginTests/Resources/Foo/foo-messages.proto
  IntegrationTests/PluginTests/Resources/Foo/foo-service.proto
  IntegrationTests/PluginTests/Resources/FooHelloWorldAdopter.swift
  IntegrationTests/PluginTests/Resources/HelloWorld/HelloWorld.proto
  IntegrationTests/PluginTests/Resources/HelloWorld/Messages.proto
  IntegrationTests/PluginTests/Resources/HelloWorld/Service.proto
  IntegrationTests/PluginTests/Resources/HelloWorldAdopter.swift
  IntegrationTests/PluginTests/Resources/Package.swift
  IntegrationTests/PluginTests/Resources/import-directory-1-grpc-swift-proto-generator-config.json
  IntegrationTests/PluginTests/Resources/internal-grpc-swift-proto-generator-config.json
  IntegrationTests/PluginTests/Resources/public-grpc-swift-proto-generator-config.json
  dev/execute-plugin-tests.sh
  dev/plugin-tests.sh
  dev/setup-plugin-tests.sh
Labels: 🔨 semver/patch

#38 Bump dependency versions
  IntegrationTests/PluginTests/Resources/Package.swift
  Package.swift
Labels: 🔨 semver/patch

#42 CI use 6.1 nightlies
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#39 Add docs explaining generated code and its API
  Sources/GRPCProtobuf/Documentation.docc/Articles/API-stability-of-generated-code.md
  Sources/GRPCProtobuf/Documentation.docc/Articles/Understanding-the-generated-code.md
  Sources/GRPCProtobuf/Documentation.docc/Documentation.md
Labels: semver/none, area/documentation
